#include "StyleTokens.h"

#include <QtGlobal>

namespace StyleTokens {

namespace {

void replaceToken(QString& styleSheet, const char* name, const char* value) {
    styleSheet.replace(QString::fromLatin1(name), QString::fromLatin1(value));
}

void replaceToken(QString& styleSheet, const char* name, int value) {
    styleSheet.replace(QString::fromLatin1(name), QString::number(value));
}

void replaceToken(QString& styleSheet, const char* name,
                  const QString& value) {
    styleSheet.replace(QString::fromLatin1(name), value);
}

}  // namespace

namespace Colors {

QColor fromHex(const char* hex) {
    const QString value = QString::fromLatin1(hex);
    if (value.size() == 9 && value.front() == QLatin1Char('#')) {
        bool ok = false;
        const quint32 rgba = value.sliced(1).toUInt(&ok, 16);
        if (ok) {
            return QColor::fromRgb((rgba >> 24) & 0xff, (rgba >> 16) & 0xff,
                                   (rgba >> 8) & 0xff, rgba & 0xff);
        }
    }
    return QColor(value);
}

}  // namespace Colors

namespace Typography {

QString uiFontFamily() {
#if defined(Q_OS_MACOS)
    return QStringLiteral("\"PingFang SC\"");
#elif defined(Q_OS_WIN)
    return QStringLiteral("\"Microsoft YaHei UI\"");
#else
    return QStringLiteral("sans-serif");
#endif
}

QString monoFontFamily() {
#if defined(Q_OS_MACOS)
    return QStringLiteral("\"SF Mono\"");
#elif defined(Q_OS_WIN)
    return QStringLiteral("\"Cascadia Mono\"");
#else
    return QStringLiteral("monospace");
#endif
}

}  // namespace Typography

QString appStyleSheet() {
    QString styleSheet = QStringLiteral(R"QSS(
/* Generated by StyleTokens. Component code should not duplicate these values. */
QWidget {
    color: {{TEXT_PRIMARY}};
    background-color: {{BG_BASE}};
    font-family: {{FONT_UI}};
    font-size: {{TYPE_BODY}}px;
    font-weight: {{WEIGHT_BODY}};
    selection-color: {{TEXT_PRIMARY}};
    selection-background-color: {{ACCENT_DIM}};
}

QWidget[uiRole="canvas"],
QGraphicsView[uiRole="canvas"],
QScrollArea[uiRole="canvas"] {
    background-color: {{BG_CANVAS}};
    border: none;
}
QWidget[uiRole="panel"] {
    background-color: {{BG_BASE}};
    border: none;
}
QWidget[uiRole="raised"],
QFrame[uiRole="raised"] {
    background-color: {{BG_RAISED}};
    border: 1px solid {{LINE_STRONG}};
    border-radius: {{RADIUS_MEDIUM}}px;
}
QWidget[uiRole="overlay"],
QFrame[uiRole="overlay"] {
    background-color: {{BG_OVERLAY}};
    border: 1px solid {{LINE_STRONG}};
    border-radius: {{RADIUS_MEDIUM}}px;
}
QFrame[uiRole="separator"] {
    min-height: 1px;
    max-height: 1px;
    background-color: {{LINE_SUBTLE}};
    border: none;
}

QWidget#mainToolbar,
QWidget#paramsTitleBar,
QWidget#paramsPresetBar,
QWidget#paramsFooter,
QStatusBar {
    background-color: {{BG_RAISED}};
    border: none;
}
QWidget#paramsPanel,
QWidget#projectPanel {
    background-color: {{BG_BASE}};
    border: none;
}
QWidget#mainToolbar {
    border-bottom: 1px solid {{LINE_SUBTLE}};
}
QStatusBar {
    min-height: {{STATUS_HEIGHT}}px;
    max-height: {{STATUS_HEIGHT}}px;
    border-top: 1px solid {{LINE_SUBTLE}};
    color: {{TEXT_SECONDARY}};
    font-size: {{TYPE_CAPTION}}px;
}
QSplitter::handle {
    background-color: {{LINE_SUBTLE}};
}
QSplitter::handle:horizontal {
    width: 1px;
}
QSplitter::handle:vertical {
    height: 1px;
}

QLabel {
    color: {{TEXT_PRIMARY}};
    background-color: transparent;
}
QLabel[textRole="display"] {
    font-size: {{TYPE_DISPLAY}}px;
    font-weight: {{WEIGHT_DISPLAY}};
}
QLabel[textRole="title"] {
    font-size: {{TYPE_TITLE}}px;
    font-weight: {{WEIGHT_TITLE}};
}
QLabel[textRole="secondary"] {
    color: {{TEXT_SECONDARY}};
}
QLabel[textRole="faint"] {
    color: {{TEXT_FAINT}};
}
QLabel[textRole="caption"] {
    color: {{TEXT_SECONDARY}};
    font-size: {{TYPE_CAPTION}}px;
}
QLabel[textRole="mono"] {
    font-family: {{FONT_MONO}};
    font-size: {{TYPE_MONO}}px;
    font-weight: {{WEIGHT_MONO}};
}
QLabel[textRole="status"] {
    color: {{TEXT_SECONDARY}};
    font-size: {{TYPE_CAPTION}}px;
}
QLabel[statusRole="success"] {
    color: {{OK}};
}
QLabel[statusRole="warning"] {
    color: {{WARNING}};
}
QLabel[statusRole="error"] {
    color: {{ERROR}};
}
QFrame[controlRole="statusDot"] {
    min-width: {{STATUS_DOT_SIZE}}px;
    max-width: {{STATUS_DOT_SIZE}}px;
    min-height: {{STATUS_DOT_SIZE}}px;
    max-height: {{STATUS_DOT_SIZE}}px;
    background-color: {{TEXT_FAINT}};
    border: none;
    border-radius: 3px;
}
QFrame[controlRole="statusDot"][statusRole="success"] {
    background-color: {{OK}};
}
QFrame[controlRole="statusDot"][statusRole="warning"] {
    background-color: {{WARNING}};
}
QFrame[controlRole="statusDot"][statusRole="error"] {
    background-color: {{ERROR}};
}

QPushButton,
QToolButton {
    min-height: {{CONTROL_HEIGHT}}px;
    max-height: {{CONTROL_HEIGHT}}px;
    padding: 0 {{BUTTON_PADDING}}px;
    color: {{TEXT_PRIMARY}};
    background-color: transparent;
    border: 1px solid {{LINE_STRONG}};
    border-radius: {{RADIUS_SMALL}}px;
    font-size: {{TYPE_BODY}}px;
    font-weight: {{WEIGHT_SEMIBOLD}};
}
QPushButton:hover,
QToolButton:hover {
    background-color: {{BG_OVERLAY}};
}
QPushButton:pressed,
QToolButton:pressed {
    background-color: {{BG_OVERLAY}};
    border-color: {{ACCENT_DIM}};
}
QPushButton:focus,
QToolButton:focus {
    border: 2px solid {{ACCENT}};
}
QPushButton:disabled,
QToolButton:disabled {
    color: {{TEXT_FAINT}};
    background-color: transparent;
    border-color: {{LINE_SUBTLE}};
}

QPushButton[variant="primary"],
QToolButton[variant="primary"] {
    color: {{ACTION_TEXT}};
    background-color: {{ACTION}};
    border-color: {{ACTION}};
}
QPushButton[variant="primary"]:hover,
QToolButton[variant="primary"]:hover {
    background-color: {{ACTION_HOVER}};
    border-color: {{ACTION_HOVER}};
}
QPushButton[variant="primary"]:pressed,
QToolButton[variant="primary"]:pressed {
    background-color: {{ACTION_PRESSED}};
    border-color: {{ACTION_PRESSED}};
}
QPushButton[variant="primary"]:focus,
QToolButton[variant="primary"]:focus {
    border: 2px solid {{ACCENT}};
}
QPushButton[variant="primary"]:disabled,
QToolButton[variant="primary"]:disabled {
    color: {{TEXT_FAINT}};
    background-color: {{BG_OVERLAY}};
    border-color: {{BG_OVERLAY}};
}

QPushButton[variant="secondary"],
QToolButton[variant="secondary"] {
    color: {{TEXT_PRIMARY}};
    background-color: transparent;
    border-color: {{LINE_STRONG}};
}
QPushButton[variant="ghost"],
QToolButton[variant="ghost"] {
    color: {{TEXT_SECONDARY}};
    background-color: transparent;
    border-color: transparent;
}
QPushButton[variant="ghost"]:hover,
QToolButton[variant="ghost"]:hover {
    color: {{TEXT_PRIMARY}};
    background-color: {{BG_OVERLAY}};
}
QPushButton[variant="ghost"]:disabled,
QToolButton[variant="ghost"]:disabled,
QPushButton[variant="danger"]:disabled,
QToolButton[variant="danger"]:disabled,
QPushButton[variant="icon"]:disabled,
QToolButton[variant="icon"]:disabled {
    color: {{TEXT_FAINT}};
    background-color: transparent;
    border-color: transparent;
}
QPushButton[variant="danger"],
QToolButton[variant="danger"] {
    color: {{ERROR}};
    background-color: transparent;
    border-color: {{ERROR}};
}
QPushButton[variant="danger"]:pressed,
QToolButton[variant="danger"]:pressed {
    color: {{ERROR}};
    background-color: {{BG_OVERLAY}};
    border-color: {{ERROR}};
}
QPushButton[variant="icon"],
QToolButton[variant="icon"] {
    min-width: {{ICON_BUTTON_SIZE}}px;
    max-width: {{ICON_BUTTON_SIZE}}px;
    min-height: {{ICON_BUTTON_SIZE}}px;
    max-height: {{ICON_BUTTON_SIZE}}px;
    padding: 0;
    color: {{TEXT_SECONDARY}};
    background-color: transparent;
    border-color: transparent;
}
QPushButton[variant="icon"]:hover,
QToolButton[variant="icon"]:hover {
    color: {{TEXT_PRIMARY}};
    background-color: {{BG_OVERLAY}};
}
QPushButton[sizeRole="dialog"],
QToolButton[sizeRole="dialog"] {
    min-height: {{DIALOG_CONTROL_HEIGHT}}px;
    max-height: {{DIALOG_CONTROL_HEIGHT}}px;
}

QLineEdit,
QPlainTextEdit,
QTextEdit,
QSpinBox,
QDoubleSpinBox,
QDateEdit,
QTimeEdit,
QDateTimeEdit,
QComboBox {
    min-height: {{CONTROL_HEIGHT}}px;
    max-height: {{CONTROL_HEIGHT}}px;
    padding: 0 {{INPUT_PADDING}}px;
    color: {{TEXT_PRIMARY}};
    background-color: {{BG_RAISED}};
    border: 1px solid {{LINE_SUBTLE}};
    border-radius: {{RADIUS_SMALL}}px;
    selection-color: {{TEXT_PRIMARY}};
    selection-background-color: {{ACCENT_DIM}};
}
QPlainTextEdit,
QTextEdit {
    min-height: 52px;
    max-height: 16777215px;
    padding: {{INPUT_PADDING}}px;
}
QLineEdit:hover,
QPlainTextEdit:hover,
QTextEdit:hover,
QSpinBox:hover,
QDoubleSpinBox:hover,
QComboBox:hover {
    border-color: {{LINE_STRONG}};
}
QLineEdit:focus,
QPlainTextEdit:focus,
QTextEdit:focus,
QSpinBox:focus,
QDoubleSpinBox:focus,
QComboBox:focus {
    border-color: {{ACCENT}};
}
QLineEdit:disabled,
QPlainTextEdit:disabled,
QTextEdit:disabled,
QSpinBox:disabled,
QDoubleSpinBox:disabled,
QComboBox:disabled {
    color: {{TEXT_FAINT}};
    background-color: {{BG_BASE}};
    border-color: {{LINE_SUBTLE}};
}
QLineEdit[readOnly="true"] {
    color: {{TEXT_SECONDARY}};
}
QComboBox::drop-down {
    width: 26px;
    border: none;
}
QComboBox QAbstractItemView {
    min-height: {{COMBO_ITEM_HEIGHT}}px;
    color: {{TEXT_PRIMARY}};
    background-color: {{BG_RAISED}};
    border: 1px solid {{LINE_STRONG}};
    border-radius: {{RADIUS_MEDIUM}}px;
    outline: 0;
    selection-color: {{ACCENT}};
    selection-background-color: {{BG_OVERLAY}};
}

QCheckBox,
QRadioButton {
    min-height: {{CONTROL_HEIGHT}}px;
    spacing: 8px;
    color: {{TEXT_PRIMARY}};
    background-color: transparent;
}
QCheckBox:hover,
QRadioButton:hover {
    color: {{ACCENT_STRONG}};
}
QCheckBox:disabled,
QRadioButton:disabled {
    color: {{TEXT_FAINT}};
}
QCheckBox::indicator,
QRadioButton::indicator {
    width: {{CHECK_SIZE}}px;
    height: {{CHECK_SIZE}}px;
    background-color: {{BG_RAISED}};
    border: 1px solid {{LINE_STRONG}};
}
QCheckBox::indicator {
    border-radius: {{RADIUS_SMALL}}px;
}
QRadioButton::indicator {
    border-radius: 7px;
}
QCheckBox::indicator:checked,
QRadioButton::indicator:checked {
    background-color: {{ACCENT}};
    border-color: {{ACCENT}};
}
QCheckBox::indicator:disabled,
QRadioButton::indicator:disabled {
    background-color: {{BG_OVERLAY}};
    border-color: {{LINE_SUBTLE}};
}
/* Toggle geometry is finalized by the custom-painted control. */
QCheckBox[controlRole="toggle"]::indicator {
    width: {{TOGGLE_WIDTH}}px;
    height: {{TOGGLE_HEIGHT}}px;
    background-color: {{BG_OVERLAY}};
    border: none;
    border-radius: 9px;
}
QCheckBox[controlRole="toggle"]::indicator:checked {
    background-color: {{ACCENT_DIM}};
}

QSlider {
    min-height: 20px;
    background-color: transparent;
}
QSlider::groove:horizontal {
    height: {{SLIDER_TRACK}}px;
    background-color: {{LINE_SUBTLE}};
    border: none;
    border-radius: 1px;
}
QSlider::sub-page:horizontal {
    height: {{SLIDER_TRACK}}px;
    background-color: {{ACCENT}};
    border-radius: 1px;
}
QSlider::handle:horizontal {
    width: {{SLIDER_HANDLE}}px;
    height: {{SLIDER_HANDLE}}px;
    margin: -5px 0;
    background-color: {{BG_BASE}};
    border: 2px solid {{ACCENT}};
    border-radius: 6px;
}
QSlider::handle:horizontal:hover,
QSlider::handle:horizontal:pressed {
    background-color: {{ACCENT}};
}
QSlider::groove:horizontal:disabled,
QSlider::sub-page:horizontal:disabled {
    background-color: {{LINE_SUBTLE}};
}
QSlider::handle:horizontal:disabled {
    background-color: {{BG_OVERLAY}};
    border-color: {{LINE_SUBTLE}};
}

QTabWidget::pane {
    background-color: {{BG_BASE}};
    border: none;
    border-top: 1px solid {{LINE_SUBTLE}};
}
QTabBar {
    background-color: {{BG_BASE}};
}
QTabBar::tab {
    min-height: {{TAB_HEIGHT}}px;
    padding: 0 10px;
    color: {{TEXT_SECONDARY}};
    background-color: transparent;
    border: none;
    border-bottom: 2px solid transparent;
}
QTabBar::tab:hover {
    color: {{TEXT_PRIMARY}};
}
QTabBar::tab:selected {
    color: {{TEXT_PRIMARY}};
    border-bottom-color: {{ACCENT}};
}

QGroupBox {
    margin-top: {{SECTION_GAP}}px;
    padding-top: 8px;
    color: {{TEXT_PRIMARY}};
    background-color: transparent;
    border: none;
    border-top: 1px solid {{LINE_SUBTLE}};
    font-size: {{TYPE_TITLE}}px;
    font-weight: {{WEIGHT_TITLE}};
}
QGroupBox::title {
    subcontrol-origin: margin;
    subcontrol-position: top left;
    left: 0;
    padding: 0 8px 0 0;
    color: {{TEXT_PRIMARY}};
    background-color: {{BG_BASE}};
}

QListView,
QTreeView,
QTableView {
    color: {{TEXT_PRIMARY}};
    background-color: {{BG_BASE}};
    alternate-background-color: {{BG_RAISED}};
    border: none;
    outline: 0;
}
QListView::item,
QTreeView::item,
QTableView::item {
    min-height: {{COMBO_ITEM_HEIGHT}}px;
    border: none;
}
QListView::item:hover,
QTreeView::item:hover,
QTableView::item:hover {
    background-color: {{BG_OVERLAY}};
}
QListView::item:selected,
QTreeView::item:selected,
QTableView::item:selected {
    color: {{TEXT_PRIMARY}};
    background-color: {{ACCENT_DIM}};
}
QHeaderView::section {
    padding: 0 8px;
    color: {{TEXT_SECONDARY}};
    background-color: {{BG_RAISED}};
    border: none;
    border-right: 1px solid {{LINE_SUBTLE}};
    border-bottom: 1px solid {{LINE_SUBTLE}};
}

QProgressBar {
    min-height: {{PROGRESS_HEIGHT}}px;
    max-height: {{PROGRESS_HEIGHT}}px;
    color: transparent;
    background-color: {{LINE_SUBTLE}};
    border: none;
}
QProgressBar::chunk {
    background-color: {{ACCENT}};
}
QProgressBar[controlRole="progressLine"] {
    min-height: {{PROGRESS_HEIGHT}}px;
    max-height: {{PROGRESS_HEIGHT}}px;
    border-radius: 0;
}

QMenu {
    padding: 4px;
    color: {{TEXT_PRIMARY}};
    background-color: {{BG_RAISED}};
    border: 1px solid {{LINE_STRONG}};
    border-radius: {{RADIUS_MEDIUM}}px;
}
QMenu::item {
    min-height: {{CONTROL_HEIGHT}}px;
    padding: 0 24px 0 10px;
    background-color: transparent;
    border-radius: {{RADIUS_SMALL}}px;
}
QMenu::item:selected {
    background-color: {{BG_OVERLAY}};
}
QMenu::item:disabled {
    color: {{TEXT_FAINT}};
}
QMenu::separator {
    height: 1px;
    margin: 4px 6px;
    background-color: {{LINE_SUBTLE}};
}

QDialog,
QMessageBox {
    color: {{TEXT_PRIMARY}};
    background-color: {{BG_BASE}};
}
QToolTip {
    padding: 5px 7px;
    color: {{TEXT_PRIMARY}};
    background-color: {{BG_RAISED}};
    border: 1px solid {{LINE_STRONG}};
    border-radius: {{RADIUS_SMALL}}px;
    font-size: {{TYPE_CAPTION}}px;
}

QScrollBar:vertical {
    width: 8px;
    margin: 2px;
    background-color: transparent;
}
QScrollBar::handle:vertical {
    min-height: 24px;
    background-color: {{LINE_STRONG}};
    border: none;
    border-radius: {{RADIUS_SMALL}}px;
}
QScrollBar::handle:vertical:hover {
    background-color: {{TEXT_FAINT}};
}
QScrollBar:horizontal {
    height: 8px;
    margin: 2px;
    background-color: transparent;
}
QScrollBar::handle:horizontal {
    min-width: 24px;
    background-color: {{LINE_STRONG}};
    border: none;
    border-radius: {{RADIUS_SMALL}}px;
}
QScrollBar::handle:horizontal:hover {
    background-color: {{TEXT_FAINT}};
}
QScrollBar::add-line,
QScrollBar::sub-line,
QScrollBar::add-page,
QScrollBar::sub-page {
    width: 0;
    height: 0;
    background-color: transparent;
    border: none;
}
)QSS");

    replaceToken(styleSheet, "{{BG_CANVAS}}", Colors::kBackgroundCanvas);
    replaceToken(styleSheet, "{{BG_BASE}}", Colors::kBackgroundBase);
    replaceToken(styleSheet, "{{BG_RAISED}}", Colors::kBackgroundRaised);
    replaceToken(styleSheet, "{{BG_OVERLAY}}", Colors::kBackgroundOverlay);
    replaceToken(styleSheet, "{{LINE_SUBTLE}}", Colors::kLineSubtle);
    replaceToken(styleSheet, "{{LINE_STRONG}}", Colors::kLineStrong);
    replaceToken(styleSheet, "{{TEXT_PRIMARY}}", Colors::kTextPrimary);
    replaceToken(styleSheet, "{{TEXT_SECONDARY}}", Colors::kTextSecondary);
    replaceToken(styleSheet, "{{TEXT_FAINT}}", Colors::kTextFaint);
    replaceToken(styleSheet, "{{ACCENT}}", Colors::kAccent);
    replaceToken(styleSheet, "{{ACCENT_STRONG}}", Colors::kAccentStrong);
    replaceToken(styleSheet, "{{ACCENT_DIM}}", Colors::kAccentDim);
    replaceToken(styleSheet, "{{ACTION}}", Colors::kAction);
    replaceToken(styleSheet, "{{ACTION_HOVER}}", Colors::kActionHover);
    replaceToken(styleSheet, "{{ACTION_PRESSED}}", Colors::kActionPressed);
    replaceToken(styleSheet, "{{ACTION_TEXT}}", Colors::kActionText);
    replaceToken(styleSheet, "{{OK}}", Colors::kOk);
    replaceToken(styleSheet, "{{WARNING}}", Colors::kWarning);
    replaceToken(styleSheet, "{{ERROR}}", Colors::kError);

    replaceToken(styleSheet, "{{FONT_UI}}", Typography::uiFontFamily());
    replaceToken(styleSheet, "{{FONT_MONO}}", Typography::monoFontFamily());
    replaceToken(styleSheet, "{{TYPE_DISPLAY}}", Typography::kDisplaySize);
    replaceToken(styleSheet, "{{TYPE_TITLE}}", Typography::kTitleSize);
    replaceToken(styleSheet, "{{TYPE_BODY}}", Typography::kBodySize);
    replaceToken(styleSheet, "{{TYPE_CAPTION}}", Typography::kCaptionSize);
    replaceToken(styleSheet, "{{TYPE_MONO}}", Typography::kMonoSize);
    replaceToken(styleSheet, "{{WEIGHT_DISPLAY}}",
                 Typography::kDisplayWeight);
    replaceToken(styleSheet, "{{WEIGHT_TITLE}}", Typography::kTitleWeight);
    replaceToken(styleSheet, "{{WEIGHT_BODY}}", Typography::kBodyWeight);
    replaceToken(styleSheet, "{{WEIGHT_MONO}}", Typography::kMonoWeight);
    replaceToken(styleSheet, "{{WEIGHT_SEMIBOLD}}",
                 Typography::kTitleWeight);

    replaceToken(styleSheet, "{{RADIUS_SMALL}}", Radius::kSmall);
    replaceToken(styleSheet, "{{RADIUS_MEDIUM}}", Radius::kMedium);
    replaceToken(styleSheet, "{{CONTROL_HEIGHT}}", Controls::kCompactHeight);
    replaceToken(styleSheet, "{{DIALOG_CONTROL_HEIGHT}}",
                 Controls::kDialogHeight);
    replaceToken(styleSheet, "{{ICON_BUTTON_SIZE}}",
                 Controls::kIconButtonSize);
    replaceToken(styleSheet, "{{BUTTON_PADDING}}",
                 Controls::kButtonHorizontalPadding);
    replaceToken(styleSheet, "{{INPUT_PADDING}}",
                 Controls::kInputHorizontalPadding);
    replaceToken(styleSheet, "{{CHECK_SIZE}}",
                 Controls::kCheckIndicatorSize);
    replaceToken(styleSheet, "{{COMBO_ITEM_HEIGHT}}",
                 Controls::kComboItemHeight);
    replaceToken(styleSheet, "{{TAB_HEIGHT}}", Controls::kTabHeight);
    replaceToken(styleSheet, "{{SLIDER_TRACK}}",
                 Controls::kSliderTrackHeight);
    replaceToken(styleSheet, "{{SLIDER_HANDLE}}",
                 Controls::kSliderHandleSize);
    replaceToken(styleSheet, "{{TOGGLE_WIDTH}}", Controls::kToggleWidth);
    replaceToken(styleSheet, "{{TOGGLE_HEIGHT}}", Controls::kToggleHeight);
    replaceToken(styleSheet, "{{PROGRESS_HEIGHT}}",
                 Controls::kProgressHeight);
    replaceToken(styleSheet, "{{STATUS_DOT_SIZE}}",
                 Controls::kStatusDotSize);
    replaceToken(styleSheet, "{{STATUS_HEIGHT}}", Layout::kStatusBarHeight);
    replaceToken(styleSheet, "{{SECTION_GAP}}", Spacing::kSectionGap);

    return styleSheet;
}

}  // namespace StyleTokens
